### ISSUE TITLE
About the framework

### ISSUE THREAD

**Issue by mohankumarvarma0007** [Ajaysinh1290/College-Management-System-In-Java#9]
which framework is used for this project? can i use this project as a final year project?

**Comment by Ajaysinh1290** [comment]
Java swing UI framework is used for UI.
Yes, you can use this project as final year project.

**Comment by mohankumarvarma0007** [comment]
ok bro thanks for that,but how to edit or change the course related info
after we save the courses.

**Comment by Ajaysinh1290** [comment]
You can edit the course related information after saving the courses

**Comment by mohankumarvarma0007** [comment]
bro start the database server first error is coming.how to solve this error.
